// <auto-generated />
namespace Uber.Data
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddShortCodetoProductProductType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddShortCodetoProductProductType));
        
        string IMigrationMetadata.Id
        {
            get { return "201304210547329_Add-ShortCode-to-Product-ProductType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
