// <auto-generated />
namespace Uber.Data
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class OrderOrderItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderOrderItems));
        
        string IMigrationMetadata.Id
        {
            get { return "201304210542171_Order-OrderItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
